version: '3.8'
services:
  gatsby:
    build: 
      context: ./frontend
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
     - /app/node_modules/