version: "3.7"

services:
  nemos:
    build: ./nemos # link to subfolder of mono-repo
    ports:
      - "9000:9000"
    volumes:
      - ./nemos:/app
    restart: "no"
    depends_on:
      - db
      - backend
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
