version: "3.8"

services:
  nemos:
    build: ./nemos
    command: gatsby develop -H 0.0.0.0 -p 9000
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./nemos/:/app/
    working_dir: /app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1
    restart: "no"
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=mnemos
      - POSTGRES_PASSWORD=mnemos
      - POSTGRES_DB=mnemos_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env.dev

volumes:
  postgres_data:
